openapi: 3.0.3
info:
  title: Capsule Memory API
  version: 0.1.0
servers:
  - url: http://localhost:3000
paths:
  /v1/memory:
    post:
      summary: Add memory capsule
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
              properties:
                content:
                  type: string
                meta:
                  $ref: "#/components/schemas/CapsuleMetaPartial"
      responses:
        "200":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CapsuleMeta"
  /v1/memory/{id}:
    get:
      summary: Get memory capsule
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - content
                  - meta
                properties:
                  content:
                    type: string
                  meta:
                    $ref: "#/components/schemas/CapsuleMeta"
        "404":
          description: Not found
  /v1/search:
    post:
      summary: Search memories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                k:
                  type: integer
                  minimum: 1
                  maximum: 50
                  default: 5
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - results
                properties:
                  results:
                    type: array
                    items:
                      type: object
                      required:
                        - id
                        - score
                      properties:
                        id:
                          type: string
                        score:
                          type: number
components:
  schemas:
    CapsuleMeta:
      type: object
      required:
        - id
        - createdAt
      properties:
        id:
          type: string
        org:
          type: string
        project:
          type: string
        subject:
          type: string
        type:
          type: string
        tags:
          type: array
          items:
            type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        ttl:
          type: integer
        expiryAt:
          type: string
        pinned:
          type: boolean
        importance:
          type: number
        recencyScore:
          type: number
        source:
          type: object
          properties:
            app:
              type: string
            connector:
              type: string
            url:
              type: string
            fileId:
              type: string
            spanId:
              type: string
        provenance:
          type: array
          items:
            type: string
        acl:
          type: object
          properties:
            visibility:
              type: string
              enum:
                - private
                - org
                - public
            roles:
              type: array
              items:
                type: string
        pii:
          type: object
          additionalProperties:
            type: boolean
    CapsuleMetaPartial:
      allOf:
        - $ref: "#/components/schemas/CapsuleMeta"
